import type { IconMeta } from './types';

// Metadata only — no SVG payloads loaded here
export const ICON_REGISTRY: IconMeta[] = [
  // Lucide icons — add all relevant ones
  { name: 'Home', slug: 'home', library: 'lucide', category: 'UI', tags: ['house', 'main', 'start', 'dashboard'] },
  { name: 'User', slug: 'user', library: 'lucide', category: 'People', tags: ['person', 'account', 'profile', 'avatar'] },
  { name: 'Settings', slug: 'settings', library: 'lucide', category: 'UI', tags: ['gear', 'config', 'preferences', 'options'] },
  { name: 'Search', slug: 'search', library: 'lucide', category: 'UI', tags: ['magnify', 'find', 'lookup', 'filter'] },
  { name: 'Bell', slug: 'bell', library: 'lucide', category: 'Communication', tags: ['notification', 'alert', 'reminder'] },
  { name: 'Mail', slug: 'mail', library: 'lucide', category: 'Communication', tags: ['email', 'message', 'inbox', 'envelope'] },
  { name: 'Phone', slug: 'phone', library: 'lucide', category: 'Communication', tags: ['call', 'contact', 'mobile'] },
  { name: 'Database', slug: 'database', library: 'lucide', category: 'Tech', tags: ['storage', 'server', 'sql', 'data'] },
  { name: 'Cloud', slug: 'cloud', library: 'lucide', category: 'Tech', tags: ['server', 'hosting', 'aws', 'upload', 'storage'] },
  { name: 'Lock', slug: 'lock', library: 'lucide', category: 'Security', tags: ['secure', 'auth', 'password', 'private'] },
  { name: 'Shield', slug: 'shield', library: 'lucide', category: 'Security', tags: ['protect', 'safe', 'guard', 'security'] },
  { name: 'ArrowRight', slug: 'arrow-right', library: 'lucide', category: 'Arrows', tags: ['next', 'forward', 'direction'] },
  { name: 'ArrowLeft', slug: 'arrow-left', library: 'lucide', category: 'Arrows', tags: ['back', 'previous', 'direction'] },
  { name: 'ArrowUp', slug: 'arrow-up', library: 'lucide', category: 'Arrows', tags: ['up', 'direction', 'increase'] },
  { name: 'ArrowDown', slug: 'arrow-down', library: 'lucide', category: 'Arrows', tags: ['down', 'direction', 'decrease'] },
  { name: 'ChevronRight', slug: 'chevron-right', library: 'lucide', category: 'Arrows', tags: ['caret', 'expand', 'next'] },
  { name: 'File', slug: 'file', library: 'lucide', category: 'Files', tags: ['document', 'page', 'paper'] },
  { name: 'Folder', slug: 'folder', library: 'lucide', category: 'Files', tags: ['directory', 'container', 'storage'] },
  { name: 'Download', slug: 'download', library: 'lucide', category: 'Files', tags: ['save', 'export', 'get'] },
  { name: 'Upload', slug: 'upload', library: 'lucide', category: 'Files', tags: ['import', 'send', 'push'] },
  { name: 'Trash', slug: 'trash', library: 'lucide', category: 'UI', tags: ['delete', 'remove', 'bin', 'clear'] },
  { name: 'Edit', slug: 'edit', library: 'lucide', category: 'UI', tags: ['pencil', 'write', 'modify', 'change'] },
  { name: 'Plus', slug: 'plus', library: 'lucide', category: 'UI', tags: ['add', 'create', 'new', 'insert'] },
  { name: 'X', slug: 'x', library: 'lucide', category: 'UI', tags: ['close', 'remove', 'cancel', 'cross'] },
  { name: 'Check', slug: 'check', library: 'lucide', category: 'UI', tags: ['tick', 'done', 'confirm', 'success'] },
  { name: 'AlertCircle', slug: 'alert-circle', library: 'lucide', category: 'Status', tags: ['warning', 'error', 'info', 'danger'] },
  { name: 'CheckCircle', slug: 'check-circle', library: 'lucide', category: 'Status', tags: ['success', 'done', 'verified', 'complete'] },
  { name: 'Info', slug: 'info', library: 'lucide', category: 'Status', tags: ['information', 'help', 'details', 'about'] },
  { name: 'Star', slug: 'star', library: 'lucide', category: 'UI', tags: ['favorite', 'bookmark', 'rating', 'featured'] },
  { name: 'Heart', slug: 'heart', library: 'lucide', category: 'UI', tags: ['like', 'love', 'favorite', 'health'] },
  { name: 'Zap', slug: 'zap', library: 'lucide', category: 'Status', tags: ['lightning', 'fast', 'power', 'energy', 'flash'] },
  { name: 'Globe', slug: 'globe', library: 'lucide', category: 'Tech', tags: ['web', 'internet', 'world', 'network'] },
  { name: 'Link', slug: 'link', library: 'lucide', category: 'Tech', tags: ['url', 'chain', 'connect', 'href'] },
  { name: 'Code', slug: 'code', library: 'lucide', category: 'Tech', tags: ['programming', 'developer', 'script', 'brackets'] },
  { name: 'Terminal', slug: 'terminal', library: 'lucide', category: 'Tech', tags: ['console', 'bash', 'cli', 'command'] },
  { name: 'Monitor', slug: 'monitor', library: 'lucide', category: 'Devices', tags: ['screen', 'computer', 'desktop', 'display'] },
  { name: 'Smartphone', slug: 'smartphone', library: 'lucide', category: 'Devices', tags: ['mobile', 'phone', 'ios', 'android'] },
  { name: 'Wifi', slug: 'wifi', library: 'lucide', category: 'Tech', tags: ['network', 'internet', 'connection', 'signal'] },
  { name: 'Cpu', slug: 'cpu', library: 'lucide', category: 'Tech', tags: ['processor', 'chip', 'hardware', 'compute'] },
  { name: 'Server', slug: 'server', library: 'lucide', category: 'Tech', tags: ['backend', 'hosting', 'rack', 'infrastructure'] },
  { name: 'GitBranch', slug: 'git-branch', library: 'lucide', category: 'Dev', tags: ['git', 'version', 'branch', 'fork'] },
  { name: 'GitCommit', slug: 'git-commit', library: 'lucide', category: 'Dev', tags: ['commit', 'git', 'save', 'version'] },
  { name: 'Package', slug: 'package', library: 'lucide', category: 'Dev', tags: ['npm', 'module', 'library', 'dependency'] },
  { name: 'Layers', slug: 'layers', library: 'lucide', category: 'Design', tags: ['stack', 'depth', 'level', 'z-index'] },
  { name: 'Layout', slug: 'layout', library: 'lucide', category: 'Design', tags: ['template', 'grid', 'structure', 'wireframe'] },
  { name: 'Palette', slug: 'palette', library: 'lucide', category: 'Design', tags: ['color', 'paint', 'art', 'theme'] },
  { name: 'Image', slug: 'image', library: 'lucide', category: 'Media', tags: ['photo', 'picture', 'png', 'jpg'] },
  { name: 'Video', slug: 'video', library: 'lucide', category: 'Media', tags: ['film', 'movie', 'camera', 'record'] },
  { name: 'Music', slug: 'music', library: 'lucide', category: 'Media', tags: ['audio', 'song', 'note', 'sound'] },
  { name: 'Mic', slug: 'mic', library: 'lucide', category: 'Media', tags: ['microphone', 'audio', 'voice', 'record'] },
  { name: 'Play', slug: 'play', library: 'lucide', category: 'Media', tags: ['start', 'run', 'video', 'audio'] },
  { name: 'Pause', slug: 'pause', library: 'lucide', category: 'Media', tags: ['stop', 'hold', 'wait', 'media'] },
  { name: 'Calendar', slug: 'calendar', library: 'lucide', category: 'Time', tags: ['date', 'schedule', 'event', 'month'] },
  { name: 'Clock', slug: 'clock', library: 'lucide', category: 'Time', tags: ['time', 'hour', 'timer', 'watch'] },
  { name: 'Map', slug: 'map', library: 'lucide', category: 'Navigation', tags: ['location', 'route', 'geography', 'travel'] },
  { name: 'MapPin', slug: 'map-pin', library: 'lucide', category: 'Navigation', tags: ['location', 'pin', 'place', 'marker'] },
  { name: 'Navigation', slug: 'navigation', library: 'lucide', category: 'Navigation', tags: ['direction', 'compass', 'route', 'gps'] },
  { name: 'ShoppingCart', slug: 'shopping-cart', library: 'lucide', category: 'Commerce', tags: ['cart', 'buy', 'ecommerce', 'purchase'] },
  { name: 'CreditCard', slug: 'credit-card', library: 'lucide', category: 'Commerce', tags: ['payment', 'billing', 'finance', 'card'] },
  { name: 'DollarSign', slug: 'dollar-sign', library: 'lucide', category: 'Commerce', tags: ['money', 'price', 'cost', 'currency'] },
  { name: 'BarChart', slug: 'bar-chart', library: 'lucide', category: 'Data', tags: ['graph', 'analytics', 'stats', 'chart'] },
  { name: 'LineChart', slug: 'line-chart', library: 'lucide', category: 'Data', tags: ['graph', 'trend', 'analytics', 'data'] },
  { name: 'PieChart', slug: 'pie-chart', library: 'lucide', category: 'Data', tags: ['graph', 'analytics', 'stats', 'donut'] },
  { name: 'TrendingUp', slug: 'trending-up', library: 'lucide', category: 'Data', tags: ['growth', 'increase', 'analytics', 'up'] },
  { name: 'Users', slug: 'users', library: 'lucide', category: 'People', tags: ['team', 'group', 'members', 'community'] },
  { name: 'UserPlus', slug: 'user-plus', library: 'lucide', category: 'People', tags: ['add user', 'invite', 'register', 'signup'] },
  { name: 'MessageCircle', slug: 'message-circle', library: 'lucide', category: 'Communication', tags: ['chat', 'comment', 'talk', 'bubble'] },
  { name: 'MessageSquare', slug: 'message-square', library: 'lucide', category: 'Communication', tags: ['chat', 'sms', 'comment', 'feedback'] },
  { name: 'Send', slug: 'send', library: 'lucide', category: 'Communication', tags: ['submit', 'email', 'message', 'share'] },
  { name: 'Share', slug: 'share', library: 'lucide', category: 'Communication', tags: ['send', 'export', 'post', 'social'] },
  { name: 'Bookmark', slug: 'bookmark', library: 'lucide', category: 'UI', tags: ['save', 'favorite', 'mark', 'tag'] },
  { name: 'Tag', slug: 'tag', library: 'lucide', category: 'UI', tags: ['label', 'badge', 'category', 'mark'] },
  { name: 'Filter', slug: 'filter', library: 'lucide', category: 'UI', tags: ['sort', 'refine', 'narrow', 'funnel'] },
  { name: 'RefreshCw', slug: 'refresh-cw', library: 'lucide', category: 'UI', tags: ['reload', 'sync', 'update', 'retry'] },
  { name: 'RotateCcw', slug: 'rotate-ccw', library: 'lucide', category: 'UI', tags: ['undo', 'revert', 'back', 'reset'] },
  { name: 'Copy', slug: 'copy', library: 'lucide', category: 'UI', tags: ['duplicate', 'clone', 'paste', 'clipboard'] },
  { name: 'Clipboard', slug: 'clipboard', library: 'lucide', category: 'UI', tags: ['paste', 'copy', 'task', 'notes'] },
  { name: 'LogIn', slug: 'log-in', library: 'lucide', category: 'Auth', tags: ['sign in', 'enter', 'login', 'auth'] },
  { name: 'LogOut', slug: 'log-out', library: 'lucide', category: 'Auth', tags: ['sign out', 'exit', 'logout', 'leave'] },
  { name: 'Key', slug: 'key', library: 'lucide', category: 'Auth', tags: ['password', 'auth', 'access', 'secret'] },
  { name: 'Fingerprint', slug: 'fingerprint', library: 'lucide', category: 'Auth', tags: ['biometric', 'identity', 'secure', 'touch id'] },
  { name: 'Eye', slug: 'eye', library: 'lucide', category: 'UI', tags: ['view', 'visible', 'show', 'watch'] },
  { name: 'EyeOff', slug: 'eye-off', library: 'lucide', category: 'UI', tags: ['hide', 'invisible', 'private', 'mask'] },
  { name: 'HelpCircle', slug: 'help-circle', library: 'lucide', category: 'UI', tags: ['question', 'faq', 'support', 'help'] },
  { name: 'Menu', slug: 'menu', library: 'lucide', category: 'UI', tags: ['hamburger', 'navigation', 'list', 'sidebar'] },
  { name: 'MoreHorizontal', slug: 'more-horizontal', library: 'lucide', category: 'UI', tags: ['ellipsis', 'options', 'more', 'dots'] },
  { name: 'MoreVertical', slug: 'more-vertical', library: 'lucide', category: 'UI', tags: ['ellipsis', 'options', 'more', 'dots'] },
  { name: 'Maximize', slug: 'maximize', library: 'lucide', category: 'UI', tags: ['fullscreen', 'expand', 'enlarge', 'zoom'] },
  { name: 'Minimize', slug: 'minimize', library: 'lucide', category: 'UI', tags: ['collapse', 'shrink', 'reduce', 'exit fullscreen'] },
  { name: 'Move', slug: 'move', library: 'lucide', category: 'UI', tags: ['drag', 'reorder', 'position', 'pan'] },
  { name: 'Sliders', slug: 'sliders', library: 'lucide', category: 'UI', tags: ['settings', 'controls', 'adjust', 'config'] },
  { name: 'ToggleLeft', slug: 'toggle-left', library: 'lucide', category: 'UI', tags: ['switch', 'on off', 'enable', 'disable'] },
  { name: 'Loader', slug: 'loader', library: 'lucide', category: 'Status', tags: ['loading', 'spinner', 'wait', 'progress'] },
  { name: 'Activity', slug: 'activity', library: 'lucide', category: 'Status', tags: ['pulse', 'live', 'heartbeat', 'health'] },
];

// Build a fast search index — keyed by slug for O(1) lookup
export const ICON_INDEX = new Map<string, IconMeta>(
  ICON_REGISTRY.map(icon => [icon.slug, icon])
);

// Get all unique categories
export const ICON_CATEGORIES = ['All', ...Array.from(new Set(ICON_REGISTRY.map(i => i.category))).sort()];
